import type { Metadata } from "next";
import "./globals.css";
import { inter, playFairDisplay } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${playFairDisplay.variable} antialiased min-h-dvh flex flex-col`}>
        <div className="flex-1">{children}</div>

        <footer className="p-4 flex justify-center">
          <span className="text-center text-xs text-fill-secondary-dark">2026 Amdev.</span>
        </footer>
      </body>
    </html>
  );
}
