import type { Metadata } from "next";
import "./globals.css";
import { inter, playFairDisplay } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${playFairDisplay.variable} antialiased`}>{children}</body>
    </html>
  );
}
